# Generated by Django 5.2 on 2025-04-15 17:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflowentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
